SETTINGS = {
    "TITLE":        "Ha Long Run",
    "WIDTH":        1280,
    "HEIGHT":       720,
    "FPS":          60,
    "TILE_SIZE":    64,
    "PLAYER_SPEED": 5,
    "JUMP_SPEED":   -20,
    "GRAVITY":      0.8,
    "SKY_COLOR":    (134, 194, 237),
    "BG_IMAGE":     "asset/background/BG Image.png",
    "FONT_PATH":    "font/Minecraft.ttf",
    "MAP_FILE":     "asset/data/levels/main_game.tmx",
    "TOOTH_SCALE":  2.0,
    "ITEM_SCALE":   0.75,
    "PALM_SMALL_COLLISION_SCALE": 1,
    "PALM_LARGE_COLLISION_SCALE": 1,
    "SKULL_SCALE_X": 0.75,
    "SKULL_SCALE_Y": 1,
    "HUD_COIN_SCALE": 1.45,
    "COINS_PER_HEALTH": 100,
    "COIN_ICON_VALUE": 20,
    "MAX_HEALTH": 10,
    "WATER_RISE_SPEED": 2.0,
    "WATER_RISE_DELAY": 3.0,
    "WATER_RISE_TARGET_Y": 0,
    "COLLECTIBLE_COIN_VALUES": {
        "silver": 10,
        "gold": 20,
        "diamond": 30,
        "skull": 50,
    },
    "COLLECTIBLE_HEALTH_VALUES": {
        "potion": 1,
    },
}
